### ISSUE TITLE
No tester.py or benchmark.py work with current commits

### ISSUE THREAD

**Issue by andenix** [brohrer/becca#11]
c:\root\devel\becca\trunk>tester.py
Traceback (most recent call last):
  File "C:\root\devel\becca\trunk\tester.py", line 27, in <
    from becca_world_chase_ball.chase import World
ImportError: No module named becca_world_chase_ball.chase

c:\root\devel\becca\trunk>benchmark.py
Traceback (most recent call last):
  File "C:\root\devel\becca\trunk\benchmark.py", line 17, in
    import tester
  File "C:\root\devel\becca\trunk\tester.py", line 27, in <mo
    from becca_world_chase_ball.chase import World
ImportError: No module named becca_world_chase_ball.chase

OS: Windows 7_64, Python 2.7. It used to work before. but I think I had matt2000 release back then.

**Comment by brohrer** [comment]
andenix, you most likely have a bleeding-edge commit. The most recent commit that I have tested is the 0.6.0 tagged release, https://github.com/brohrer/becca/releases/tag/0.6.0 

Alternatively, if you'd like to get your branch working, I can help you with that offline (brohrer@gmail.com)
I think all you'll need to do is comment out line 27 in tester.py and uncomment one of the preceding import lines to import one of the worlds.

**Comment by andenix** [comment]
I think I shall do that. Thanks for your timely feedback. I appreciate the help.
